replicaCount: 1

image:
  repository: dr.neuralcompany.team/ai-and-analytics/nexastack-ai/nexastack-ai-frontend/nexastack-ai-frontend
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: false # Vite preview may need to write to filesystem

service:
  type: NodePort
  port: 4173 # Match Vite's preview port
  targetPort: 4173 # Add targetPort to map to container port

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: stage-clusterissuer
  hosts:
    - host: nexastack.stage.neuralcompany.team
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-nexastack-tls
      hosts:
        - nexastack.stage.neuralcompany.team

resources:
  limits:
    cpu: 50m
    memory: 200Mi
  requests:
    cpu: 10m
    memory: 150Mi

# livenessProbe:
#   httpGet:
#     path: /
#     port: 4173 # Match container port
#   initialDelaySeconds: 5
#   periodSeconds: 10

# readinessProbe:
#   httpGet:
#     path: /
#     port: 4173 # Match container port
#   initialDelaySeconds: 5
#   timeoutSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: logs-volume
    emptyDir: {}
  - name: vite-temp-volume
    emptyDir: {} # New volume for Vite temp files

volumeMounts:
  - name: tmp-volume
    mountPath: /tmp
  - name: logs-volume
    mountPath: /app/logs # Adjust to a path Vite can write to, avoid Apache-specific paths
  - name: vite-temp-volume
    mountPath: /app/node_modules/.vite-temp # Mount for Vite temp files

nodeSelector: {}
tolerations: []
affinity: {}
